export const info = {
    name: 'ollama_ocr',
    icon: 'logo/ollama.png',
    structuredOutput: true,
};

// 专用视觉 OCR 自行判断语种；枚举值保持 Pot 的规范语言键，供系统回退复用。
export enum Language {
    auto = 'auto',
    zh_cn = 'zh_cn',
    zh_tw = 'zh_tw',
    mn_mo = 'mn_mo',
    en = 'en',
    ja = 'ja',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt_pt',
    pt_br = 'pt_br',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    km = 'km',
    mn_cy = 'mn_cy',
    nb_no = 'nb_no',
    nn_no = 'nn_no',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
